version: 2

updates:
- package-ecosystem: terraform
  directory: /grafana
  schedule:
    interval: daily
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-minor","version-update:semver-patch"]
- package-ecosystem: terraform
  directory: /grafana-aks
  schedule:
    interval: daily
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-minor","version-update:semver-patch"]
- package-ecosystem: terraform
  directory: /grafana-eks
  schedule:
    interval: daily
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-minor","version-update:semver-patch"]
